# Generated by Django 3.1.7 on 2021-05-16 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accno', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=120)),
                ('balance', models.IntegerField(default=0)),
                ('acnt_type', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_acno', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('accno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.accounts')),
            ],
        ),
    ]
